version: '2'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      # Topic 1 will have 1 partition and 1 replicas
      # 여러 Topic을 생성하고자 할 때는 쉼표로 구분하여 입력합니다. ex. "Topic1:1:1,Topic2:1:1"
      KAFKA_CREATE_TOPICS: "Topic1:1:1"
      KAFKA_ZOOKEEPER_CONNECT: host.docker.internal:2181
    volumes:
      - .:/var/run/docker.sock
